settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: decorachi # unique identifier
    name: decorachi
    description: 'You write code. They handle the rest.' # default=empty
    url: 'https://decorachi.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false

  - id: redpro
    name: redpro
    description: 'Built for anything connected to the Internet.'
    url: 'https://kvc.redpro.ir/'
    method: GET
    expectStatus: 200

  - id: api
    name: core api
    url: 'https://api.redpanel.co/api/site/category-main-page?number=1'
    method: GET
    expectStatus: 200
